### ISSUE TITLE
Sound issues

### ISSUE THREAD

**Issue by loredan** [agiz/youtube-mpv#22]
For some reason I had trouble with sound: while mpv was launched I couldn't hear any other sound, or sometimes it was the video that had no sound. `pavucontrol` didn't show mpv in any case.

I managed to fix the problem using `youtube-mpv.service` in user mode of `systemd` instead of `youtube-mpv@<username>` in system mode, but I just thought you should know about it.

OS Archlinux, WM Awesome

**Comment by agiz** [comment]
Thank you for your input. Can you make a PR? Perhaps @jamietanna can comment on this.

**Comment by jamietanna** [comment]
Hi @loredan, - I believe that Arch by default runs Pulseaudio as the user, whereas on other distros it _may_ be run as the root user. I will look into this and see if I can find differences between distros. I would recommend that you use the user mode unit file for now.
