### ISSUE TITLE
Option to pass YouTube URL directly to mpv

### ISSUE THREAD

**Issue by parkerlreed** [agiz/youtube-mpv#27]
I would rather let mpv and its ytdl hook handle the format negotiation than this script. Hard coding it to a format is silly given that mpv and ytdl support playing DASH formats if you pass the YouTube URL as it is. I've tried editing the server file myself but haven't been able to get it working as of yet.

**Comment by parkerlreed** [comment]
Aha figured out what line to edit to do this manually https://github.com/agiz/youtube-mpv/blob/master/ytdl_server.py#L111

Change 

````
        command.append(video_url)
````

to

````
        command.append(yt_url)
````

**Comment by realazizk** [comment]
@parkerlreed  yes you can do that but the problem will be in passing other options like t, this solves it agiz/youtube-mpv#29
