### ISSUE TITLE
OPTS seems to be ignored

### ISSUE THREAD

**Issue by parkerlreed** [agiz/youtube-mpv#32]
````
HOST = '127.0.0.1'
PORT = 9000
PLAYER = 'mpv'
OPTS = '--no-terminal -vo=opengl --hwdec=vaapi --fs --ytdl-format="bestvideo[ext=mp4]+bestaudio[ext=m4a]"'
NOTIFY_COMMAND = 'notify-send'
````

I tried using that after #29 was merged and both the fullscreen and format selection have no affect. Is there some place else I need to specify this?

@mohamed-aziz

**Comment by realazizk** [comment]
@parkerlreed shit sorry #33 should fix it

**Comment by parkerlreed** [comment]
Works great! I even learned something new with that shell expansion import, so that's neat.
